# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Set stage env
        run: echo '::set-output name=STAGE_ENV::staging'
        id: stage-env

      - name: Replace stage env string in Dockerfile
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "pnpm run start"
          replace: "pnpm run start:${{ steps.stage-env.outputs.STAGE_ENV }}"
          include: "Dockerfile"

      - name: Print Dockerfile
        run: cat Dockerfile

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: HelloWorld
          environment_name: Helloworld-staging
          version_label: "helloworld-${{ github.run_id }}-${{ github.run_number }}"
          region: us-east-2
          deployment_package: deploy.zip
